DO $$ BEGIN BEGIN CREATE TYPE user_role AS ENUM ('ADMIN', 'USER');
EXCEPTION
WHEN duplicate_object THEN NULL;
END;
END;
$$;
CREATE TABLE IF NOT EXISTS "users" (
  id UUID PRIMARY KEY,
  email VARCHAR(256) NOT NULL,
  google_id VARCHAR(256) NOT NULL,
  first_name VARCHAR(64) NOT NULL,
  last_name VARCHAR(64) NOT NULL,
  phone VARCHAR(16) NOT NULL,
  profile_url VARCHAR(256) NOT NULL,
  role user_role DEFAULT 'USER',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "session" (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  ip_address VARCHAR(64) NOT NULL,
  user_agent VARCHAR(256) NOT NULL,
  expired_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES "users"(id)
);