CREATE TABLE IF NOT EXISTS "tags" (
  id SERIAL PRIMARY KEY,
  label VARCHAR(255) NOT NULL,
  "show" BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "product_tags" (
  id SERIAL PRIMARY KEY,
  product_id UUID NOT NULL,
  tag_id SERIAL NOT NULL,
  FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);