CREATE TABLE IF NOT EXISTS "favorite" (
  user_id UUID NOT NULL,
  product_id UUID NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, product_id),
  FOREIGN KEY (user_id) REFERENCES "users"(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES "product"(id) ON DELETE CASCADE
);