stages:
  - test
  - build

image: golang:1.23.1

lint:
  image: golangci/golangci-lint:v1.56.2
  stage: test
  script:
    - go vet
    - golangci-lint run 
    
build:
  stage: build
  script:
    - go mod download
    - go build
