stages:
  - test
  - build

image: golang:1.23.1


build:
  stage: build
  script:
    - go mod download
    - go build

lint:
  stage: test
  script:
    - go mod download
    - go vet
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0
    - golangci-lint run